---
title: "Download"
author: "Sofia Salazar"
date: "5/16/2022"
output: html_document
---

### Download

With this script, each study is retrieved from the Recount3 database and turned into a RangedSummarizedExperiment-class (rse) object.

## Integrating monorail-external processed data

```{bash}
qlogin
cd /mnt/Citosina/amedina/ssalazar/meta/monorail/
mkdir human
cd human
mkdir -p annotations data_sources
cd annotations
mkdir -p exon_sums gene_sums
cd exon_sums
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.G029.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.G026.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.R109.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.F006.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.SIRV.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/exon_sums/human.exon_sums.ERCC.gtf.gz
cd ../gene_sums
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.G029.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.G026.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.R109.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.F006.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.SIRV.gtf.gz
wget http://duffel.rail.bio/recount3/human/new_annotations/gene_sums/human.gene_sums.ERCC.gtf.gz

cd ../../data_sources
mkdir metaSLE
cd metaSLE
mkdir -p base_sums exon_sums gene_sums junctions metadata
cd base_sums
rsync --progress -rav /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP*/pump_output/SRR*/*.all.bw .
cd ../exon_sums
rsync --progress -rav /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP*/unify_output/unify/SRP*.unify/exon_sums_per_study/* .
cd ../gene_sums/
rsync --progress -rav /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP*/unify_output/unify/SRP*.unify/gene_sums_per_study/* .
cd ../junctions/
rsync --progress -rav /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP*/unify_output/unify/SRP*.unify/junction_counts_per_study/* .

# metaSLE.recount_project.SRP*.MD header
# rail_id	external_id	study	project	organism	file_source	metadata_source	date_processed
# metaSLE.recount_qc.SRP*.MD header
# rail_id	study_acc	run_acc	aligned_reads%.chrm	aligned_reads%.chrx	aligned_reads%.chry	bc_auc.all_reads_all_bases	bc_auc.all_reads_annotated_bases	bc_auc.unique_reads_all_bases	bc_auc.unique_reads_annotated_bases	bc_auc.all_%	bc_auc.unique_%	bc_frag.count	bc_frag.kallisto_count	bc_frag.kallisto_mean_length	bc_frag.mean_length	bc_frag.mode_length	bc_frag.mode_length_count	exon_fc.all_%	exon_fc.unique_%	exon_fc_count_all.total	exon_fc_count_all.assigned	exon_fc_count_unique.total	exon_fc_count_unique.assigned	gene_fc.all_%	gene_fc.unique_%	gene_fc_count_all.total	gene_fc_count_all.assigned	gene_fc_count_unique.total	gene_fc_count_unique.assigned	intron_sum	intron_sum_%	star.%_of_chimeric_reads	star.%_of_chimeric_reads2	star.%_of_reads_mapped_to_multiple_loci	star.%_of_reads_mapped_to_multiple_loci2	star.%_of_reads_mapped_to_too_many_loci	star.%_of_reads_mapped_to_too_many_loci2	star.%_of_reads_unmapped:_other	star.%_of_reads_unmapped:_other2	star.%_of_reads_unmapped:_too_many_mismatches	star.%_of_reads_unmapped:_too_many_mismatches2	star.%_of_reads_unmapped:_too_short	star.%_of_reads_unmapped:_too_short2	star.all_mapped_reads	star.all_mapped_reads2	star.average_input_read_length	star.average_input_read_length2	star.average_mapped_length	star.average_mapped_length2	star.deletion_average_length	star.deletion_average_length2	star.deletion_rate_per_base	star.deletion_rate_per_base2	star.insertion_average_length	star.insertion_average_length2	star.insertion_rate_per_base	star.insertion_rate_per_base2	star.mapping_speed,_million_of_reads_per_hour	star.mapping_speed,_million_of_reads_per_hour2	star.mismatch_rate_per_base,_%	star.mismatch_rate_per_base,_%2	star.number_of_chimeric_reads	star.number_of_chimeric_reads2	star.number_of_input_reads	star.number_of_input_reads2	star.number_of_reads_mapped_to_multiple_loci	star.number_of_reads_mapped_to_multiple_loci2	star.number_of_reads_mapped_to_too_many_loci	star.number_of_reads_mapped_to_too_many_loci2	star.number_of_reads_unmapped:_other	star.number_of_reads_unmapped:_other2	star.number_of_reads_unmapped:_too_many_mismatches	star.number_of_reads_unmapped:_too_many_mismatches2	star.number_of_reads_unmapped:_too_short	star.number_of_reads_unmapped:_too_short2	star.number_of_splices:_at/ac	star.number_of_splices:_at/ac2	star.number_of_splices:_annotated_(sjdb)	star.number_of_splices:_annotated_(sjdb)2	star.number_of_splices:_gc/ag	star.number_of_splices:_gc/ag2	star.number_of_splices:_gt/ag	star.number_of_splices:_gt/ag2	star.number_of_splices:_non-canonical	star.number_of_splices:_non-canonical2	star.number_of_splices:_total	star.number_of_splices:_total2	star.uniquely_mapped_reads_%	star.uniquely_mapped_reads_%2	star.uniquely_mapped_reads_number	star.uniquely_mapped_reads_number2	junction_count	junction_coverage	junction_avg_coverage	star.number_of_input_reads_both	star.all_mapped_reads_both	star.number_of_chimeric_reads_both	star.number_of_reads_mapped_to_multiple_loci_both	star.number_of_reads_mapped_to_too_many_loci_both	star.number_of_reads_unmapped:_other_both	star.number_of_reads_unmapped:_too_many_mismatches_both	star.number_of_reads_unmapped:_too_short_both	star.uniquely_mapped_reads_number_both	star.%_mapped_reads_both	star.%_chimeric_reads_both	star.%_reads_mapped_to_multiple_loci_both	star.%_reads_mapped_to_too_many_loci_both	star.%_reads_unmapped:_other_both	star.%_reads_unmapped:_too_many_mismatches_both	star.%_reads_unmapped:_too_short_both	star.uniquely_mapped_reads_%_both
cd ../metadata
mkdir -p 15 41 59 87
cd /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP311059/unify_output/unify/SRP311059.unify
awk -v OFS='\t' '{ print $1,$2,$3,$3,"Homo sapiens","data_sources/metaSLE","data_sources/metaSLE","2022-05-30"} ' samples.tsv | sed '1d' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/metaSLE.recount_project.SRP311059.MD
awk '{ print $3}' ids.tsv > /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/metaSLE.recount_project.SRP311059.MD
while read -r line; do sed '1d' qc_1.tsv | awk -v OFS='\t' '{ print "line",$0}' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/metaSLE.recount_qc.SRP311059.MD; sed -i "s/line/$line/g" /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/metaSLE.recount_qc.SRP311059.MD; done </mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/rail-ids.tsv
rm /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/59/SRP311059/metaSLE.recount_qc.SRP311059.MD

cd /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP111941/unify_output/unify/SRP111941.unify
mkdir -p /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941
awk -v OFS='\t' '{ print $1,$2,$3,$3,"Homo sapiens","data_sources/metaSLE","data_sources/metaSLE","2022-05-30"} ' samples.tsv | sed '1d' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/metaSLE.recount_project.SRP111941.MD
awk '{ print $3}' ids.tsv > /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/metaSLE.recount_project.SRP111941.MD
while read -r line; do sed '1d' qc_1.tsv | awk -v OFS='\t' '{ print "line",$0}' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/metaSLE.recount_qc.SRP111941.MD; sed -i "s/line/$line/g" /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/metaSLE.recount_qc.SRP111941.MD; done </mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/rail-ids.tsv
rm /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/41/SRP111941/metaSLE.recount_qc.SRP111941.MD

cd /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP296987/unify_output/unify/SRP296987.unify
mkdir -p /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987
awk -v OFS='\t' '{ print $1,$2,$3,$3,"Homo sapiens","data_sources/metaSLE","data_sources/metaSLE","2022-05-30"} ' samples.tsv | sed '1d' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/metaSLE.recount_project.SRP296987.MD
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/metaSLE.recount_project.SRP296987.MD
awk '{ print $3}' ids.tsv > /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/rail-ids.tsv
while read -r line; do sed '1d' qc_1.tsv | awk -v OFS='\t' '{ print "line",$0}' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/metaSLE.recount_qc.SRP296987.MD; sed -i "s/line/$line/g" /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/metaSLE.recount_qc.SRP296987.MD; done </mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/rail-ids.tsv
rm /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/87/SRP296987/metaSLE.recount_qc.SRP296987.MD

cd /mnt/Citosina/amedina/ssalazar/meta/monorail/SRP322015/unify_output/unify/SRP322015.unify
mkdir -p /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015
awk -v OFS='\t' '{ print $1,$2,$3,$3,"Homo sapiens","data_sources/metaSLE","data_sources/metaSLE","2022-05-30"} ' samples.tsv | sed '1d' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/metaSLE.recount_project.SRP322015.MD
awk '{ print $3}' ids.tsv > /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/metaSLE.recount_project.SRP322015.MD
while read -r line; do sed '1d' qc_1.tsv | awk -v OFS='\t' '{ print "line",$0}' >> /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/metaSLE.recount_qc.SRP322015.MD; sed -i "s/line/$line/g" /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/metaSLE.recount_qc.SRP322015.MD; done </mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/rail-ids.tsv
rm /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/rail-ids.tsv
gzip /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE/metadata/15/SRP322015/metaSLE.recount_qc.SRP322015.MD

cd /mnt/Citosina/amedina/ssalazar/meta/monorail/human/data_sources/metaSLE
# metaSLE.recount_project.MD grabbing header:
# rail_id	external_id	study	project	organism	file_source	metadata_source	date_processed
zcat metadata/*/*/*recount_project.* | head -n 1 | gzip > metadata/metaSLE.recount_project.MD.gz
zcat metadata/*/*/*recount_project.* | grep -v rail_id | gzip >> metadata/metaSLE.recount_project.MD.gz
```


```{bash}
cd /mnt/Citosina/amedina/ssalazar/meta/out
module load r/4.0.2
R
```

## Libraries

```{r}
library("recount3")
```


## Downloading and curating function

```{r}
getRecount <- function(SRA){
  # Getting the project
  rse <- create_rse(subset(human_projects, project == SRA & project_type == "data_sources"))
  # Getting read counts, scaling taking into account the total base-pair coverage for the given sample by using the area under the coverage (AUC).
  assays(rse)$counts <- transform_counts(rse)
  # Expanding SRA attributes from the sra.sample_attributes variable in the colData() slot of the RangedSummarizedExperiment-class produced by create_rse().
  rse <- expand_sra_attributes(rse)
  return(rse)
}
```

## Project download

```{r}
human_projects <- available_projects()
SRA_projects <- scan(file = "/mnt/Citosina/amedina/ssalazar/meta/data/SRA-IDs.txt", character(), sep=",")
downloads <- sapply(SRA_projects, getRecount)
saveRDS(downloads, file = "/mnt/Citosina/amedina/ssalazar/meta/out/downloads.xz", compress="xz")
```

## Session Info

```{r sessionInfo}
sessionInfo()

# R version 4.0.2 (2020-06-22)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: CentOS Linux 7 (Core)

# Matrix products: default
# BLAS:   /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRblas.so
# LAPACK: /cm/shared/apps/r/4.0.2-studio/lib64/R/lib/libRlapack.so

# locale:
 # [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 # [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 # [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 # [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 # [9] LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

# attached base packages:
# [1] parallel  stats4    stats     graphics  grDevices utils     datasets 
# [8] methods   base     

# other attached packages:
 # [1] recount3_1.0.7              SummarizedExperiment_1.20.0
 # [3] Biobase_2.50.0              GenomicRanges_1.42.0       
 # [5] GenomeInfoDb_1.26.7         IRanges_2.24.1             
 # [7] S4Vectors_0.28.1            BiocGenerics_0.36.1        
 # [9] MatrixGenerics_1.2.1        matrixStats_0.60.0         

# loaded via a namespace (and not attached):
 # [1] tidyselect_1.1.0         purrr_0.3.4              lattice_0.20-41         
 # [4] vctrs_0.3.8              generics_0.1.0           BiocFileCache_1.14.0    
 # [7] rtracklayer_1.50.0       utf8_1.2.2               blob_1.2.1              
# [10] XML_3.99-0.6             rlang_0.4.11             R.oo_1.24.0             
# [13] pillar_1.6.2             withr_2.4.2              glue_1.4.2              
# [16] DBI_1.1.1                R.utils_2.10.1           BiocParallel_1.24.1     
# [19] rappdirs_0.3.3           bit64_4.0.5              dbplyr_2.0.0            
# [22] sessioninfo_1.1.1        GenomeInfoDbData_1.2.4   lifecycle_1.0.0         
# [25] zlibbioc_1.36.0          Biostrings_2.58.0        R.methodsS3_1.8.1       
# [28] memoise_2.0.0            fastmap_1.1.0            curl_4.3.2              
# [31] fansi_0.5.0              Rcpp_1.0.7               cachem_1.0.5            
# [34] DelayedArray_0.16.3      XVector_0.30.0           bit_4.0.4               
# [37] Rsamtools_2.6.0          dplyr_1.0.3              grid_4.0.2              
# [40] cli_3.0.1                tools_4.0.2              bitops_1.0-7            
# [43] magrittr_2.0.1           RCurl_1.98-1.3           RSQLite_2.2.7           
# [46] tibble_3.1.3             crayon_1.4.1             pkgconfig_2.0.3         
# [49] ellipsis_0.3.2           Matrix_1.3-4             data.table_1.14.0       
# [52] rstudioapi_0.13          assertthat_0.2.1         httr_1.4.2              
# [55] R6_2.5.0                 GenomicAlignments_1.26.0 compiler_4.0.2
```

